//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedPerson
    {
        public int iID { get; set; }
        public int iProjectID { get; set; }
        public string vProjectName { get; set; }
        public string vAssignedPersonName { get; set; }
        public string vAssignedPersonDesignation { get; set; }
    }
}
